name: Check Latest NuGet Package Version

on:
  push:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Latest Package Version
      id: get_version
      run: echo "::set-output name=latest_version::$(dotnet show PackageName -n Example.Action -v n)"

    - name: Print Latest Package Version
      run: echo "Latest Version: ${{ steps.get_version.outputs.latest_version }}"
